<!--
<h4 class='example'>Screenshot</h4>

<div class='example'>
coming soon
</div>
-->

<h4 class='example'>Video tutorial</h4>

<div class='example'>
<a target='_blank' href='video/wave00-installation_and_first_impressions/wave00-installation_and_first_impressions.html'>Installation and First Impressions</a> (Flash-Video, 15:09 min)  
</div>

<h4 class='example'>Example model files</h4>

<div class='example'>
See <pre>svn://svn.berlios.de/wave/trunk/de.gulden.modeling.wave.example</pre>
</div>
