<p>
Raise your level of abstraction:
<dl class='concepts'>
	<li>Visually <b>plan architectures</b> and <b>implement web-applications</b> on top of the the <a href='http://framework.zend.com/' target='_blank'>Zend Framework</a></li>
	
	<li>Automatically <b>generate PHP/Zend code</b> from visual diagrams</li>
	
	<li>Work as usual inside the <b>Eclipse development environment</b></li>
</dl>
</p>

<div>
<center>
<img class='pic' src='img/screenshot_wave_03a.png'/>
</center>
</div>

<center>
<div class='downloadbox'>
<a href='?page=install'><img class='download' src='img/download.png' width='32' height='32' border='0'/></a>
<a href='?page=install'><b>Download and install</b></a>
</div>
</center>

<p>
<i>WAVE</i> is a graphical modeling environment for developing web-based software based on the <a href='http://framework.zend.com/' target='_blank'>Zend Web-Application framework</a>.
It has been created on top of the Eclipse <a href='http://www.eclipse.org/modeling/gmf/' target='_blank'>Graphical Modeling Framework (GMF)</a> and runs as
a plugin inside the <a href='http://www.eclipse.org/' target='_blank'>Eclipse</a> integrated development environment. 
</p>
